// Dodatkowe przepisy - część 2 (obiady - 60 przepisów)
const przepisyObiady = [
    // OBIADY MIĘSNE (20 przepisów)
    {id: 81, nazwa: "Kotlet schabowy z ziemniakami", skladniki: ["schab", "jajka", "bułka tarta", "ziemniaki"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 35, posilek: "obiad"},
    {id: 82, nazwa: "Pierogi z mięsem", skladniki: ["mąka", "mięso mielone", "cebula", "jajka"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 28, posilek: "obiad"},
    {id: 83, nazwa: "Gulasz węgierski", skladniki: ["wołowina", "papryka", "cebula", "pomidory w puszce"], czas: "powyżej 15 min", porcje: 4, lunchbox: true, dieta: "standard", cena_restauracja: 38, posilek: "obiad"},
    {id: 84, nazwa: "Kurczak w panierce", skladniki: ["kurczak", "jajka", "bułka tarta", "przyprawy"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 32, posilek: "obiad"},
    {id: 85, nazwa: "Spaghetti bolognese", skladniki: ["makaron", "mięso mielone", "pomidory w puszce", "cebula", "czosnek"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 35, posilek: "obiad", instrukcje: ["Pokrój cebulę i czosnek w drobną kostkę", "Podsmaż cebulę na oliwie do miękkości", "Dodaj mięso mielone, smaż rozgniatając widelcem", "Gdy mięso się zrumieni, dodaj czosnek", "Wlej pomidory z puszki, wymieszaj", "Dopraw solą, pieprzem, oregano", "Gotuj na małym ogniu 15-20 minut", "Ugotuj makaron al dente", "Wymieszaj makaron z sosem i podawaj"]},
    {id: 86, nazwa: "Kurczak teriyaki", skladniki: ["kurczak", "sos sojowy", "miód", "czosnek", "ryż"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 38, posilek: "obiad"},
    {id: 87, nazwa: "Kotlety mielone", skladniki: ["mięso mielone", "bułka tarta", "jajka", "cebula"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 30, posilek: "obiad"},
    {id: 88, nazwa: "Kurczak curry", skladniki: ["kurczak", "mleczko kokosowe", "przyprawa curry", "ryż"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 36, posilek: "obiad", instrukcje: ["Pokrój kurczaka w kostkę", "Podsmaż kurczaka na patelni do zrumienienia", "Dodaj 2 łyżki pasty curry, wymieszaj", "Wlej mleczko kokosowe", "Gotuj na małym ogniu 15 minut", "Dopraw solą, cukrem, sokiem z limonki", "Ugotuj ryż", "Podawaj curry na ryżu", "Posyp kolendrą (opcjonalnie)"]},
    {id: 89, nazwa: "Lasagne", skladniki: ["makaron lasagne", "mięso mielone", "ser żółty", "sos pomidorowy"], czas: "powyżej 15 min", porcje: 4, lunchbox: true, dieta: "standard", cena_restauracja: 40, posilek: "obiad"},
    {id: 90, nazwa: "Pulpety w sosie pomidorowym", skladniki: ["mięso mielone", "ryż", "pomidory w puszce", "cebula"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 32, posilek: "obiad"},
    {id: 91, nazwa: "Kurczak pieczony z warzywami", skladniki: ["kurczak", "ziemniaki", "marchew", "cebula"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 38, posilek: "obiad"},
    {id: 92, nazwa: "Gołąbki", skladniki: ["kapusta", "mięso mielone", "ryż", "pomidory w puszce"], czas: "powyżej 15 min", porcje: 4, lunchbox: true, dieta: "standard", cena_restauracja: 35, posilek: "obiad"},
    {id: 93, nazwa: "Schab w sosie pieczarkowym", skladniki: ["schab", "pieczarki", "śmietana", "cebula"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 38, posilek: "obiad"},
    {id: 94, nazwa: "Kurczak po chińsku", skladniki: ["kurczak", "papryka", "sos sojowy", "ryż"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 35, posilek: "obiad"},
    {id: 95, nazwa: "Hamburger domowy", skladniki: ["mięso mielone", "bułka", "ser żółty", "pomidor", "sałata"], czas: "do 15 min", porcje: 2, lunchbox: false, dieta: "standard", cena_restauracja: 32, posilek: "obiad"},
    {id: 96, nazwa: "Karkówka z grilla (patelnia)", skladniki: ["karkówka", "cebula", "przyprawy"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 35, posilek: "obiad"},
    {id: 97, nazwa: "Kurczak w sosie czosnkowym", skladniki: ["kurczak", "czosnek", "śmietana", "makaron"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 36, posilek: "obiad"},
    {id: 98, nazwa: "Tacos z mięsem", skladniki: ["tortilla", "mięso mielone", "sałata", "pomidor", "ser żółty"], czas: "do 15 min", porcje: 2, lunchbox: false, dieta: "standard", cena_restauracja: 30, posilek: "obiad"},
    {id: 99, nazwa: "Pierś kurczaka faszerowana", skladniki: ["kurczak", "ser żółty", "szynka", "szpinak mrożony"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 40, posilek: "obiad"},
    {id: 100, nazwa: "Żeberka w miodzie", skladniki: ["żeberka", "miód", "sos sojowy", "czosnek"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 42, posilek: "obiad"},
    
    // OBIADY WEGETARIAŃSKIE (20 przepisów)
    {id: 101, nazwa: "Pierogi ruskie", skladniki: ["mąka", "ziemniaki", "twaróg", "cebula"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 26, posilek: "obiad", instrukcje: ["Ugotuj ziemniaki, rozgnieć na puree", "Wymieszaj puree z twarogiem, dopraw solą", "Zrób ciasto: mąka + woda + sól, wyrabiaj 5 minut", "Rozwałkuj ciasto cienko", "Wykrawaj kółka szklanką", "Na każde kółko połóż łyżkę farszu", "Sklej brzegi mocno", "Gotuj w osolonej wodzie aż wypłyną", "Podsmaż cebulę na złoto", "Polej pierogi cebulką i śmietaną"]},
    {id: 102, nazwa: "Pizza margherita", skladniki: ["ciasto na pizzę", "sos pomidorowy", "mozarella", "bazylia"], czas: "powyżej 15 min", porcje: 2, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 28, posilek: "obiad"},
    {id: 103, nazwa: "Naleśniki z serem", skladniki: ["mąka", "mleko", "jajka", "twaróg", "cukier"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 24, posilek: "obiad"},
    {id: 104, nazwa: "Zapiekanka ziemniaczana", skladniki: ["ziemniaki", "ser żółty", "śmietana", "cebula"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 26, posilek: "obiad"},
    {id: 105, nazwa: "Frittata z warzywami", skladniki: ["jajka", "papryka", "cukinia", "ser żółty"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 28, posilek: "obiad"},
    {id: 106, nazwa: "Quesadilla z serem", skladniki: ["tortilla", "ser żółty", "papryka", "cebula"], czas: "do 15 min", porcje: 2, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 24, posilek: "obiad"},
    {id: 107, nazwa: "Risotto z pieczarkami", skladniki: ["ryż", "pieczarki", "cebula", "ser żółty"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 32, posilek: "obiad"},
    {id: 108, nazwa: "Pierogi z serem", skladniki: ["mąka", "twaróg", "jajka", "cukier"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 24, posilek: "obiad"},
    {id: 109, nazwa: "Zapiekanka makaronowa wegetariańska", skladniki: ["makaron", "ser żółty", "pomidory w puszce", "papryka"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 28, posilek: "obiad"},
    {id: 110, nazwa: "Kotlety z kaszy", skladniki: ["kasza gryczana", "jajka", "cebula", "bułka tarta"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 22, posilek: "obiad"}
];
