// Baza 50 przepisów
const przepisy = [
    {id: 1, nazwa: "Spaghetti Aglio e Olio", skladniki: ["makaron", "czosnek", "oliwa", "papryczka chili"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegańska", cena_restauracja: 28},
    {id: 2, nazwa: "Makaron z pesto i serem", skladniki: ["makaron", "pesto", "ser żółty"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 25},
    {id: 3, nazwa: "Makaron z tuńczykiem", skladniki: ["makaron", "tuńczyk w puszce", "kukurydza", "majonez"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 35},
    {id: 4, nazwa: "Carbonara 'Studencka'", skladniki: ["makaron", "boczek", "jajka", "śmietana", "pieprz"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "standard", cena_restauracja: 32},
    {id: 5, nazwa: "Makaron z twarogiem i cukrem", skladniki: ["makaron", "twaróg", "cukier", "śmietana"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 22},
    {id: 6, nazwa: "Makaron z sosem pomidorowym", skladniki: ["makaron", "przecier pomidorowy", "cebula", "ziola"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 30},
    {id: 7, nazwa: "Zapiekanka makaronowa z resztek", skladniki: ["makaron", "szynka", "ser żółty", "sos pomidorowy"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 38},
    {id: 8, nazwa: "Makaron ze szpinakiem i fetą", skladniki: ["makaron", "szpinak mrożony", "ser feta", "czosnek"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 30},
    {id: 9, nazwa: "Smażony ryż z jajkiem", skladniki: ["ryż", "jajka", "szczypiorek", "sos sojowy"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 28},
    {id: 10, nazwa: "Ryż z jabłkiem i cynamonem", skladniki: ["ryż", "jabłko", "cynamon", "jogurt"], czas: "powyżej 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 20},
    {id: 11, nazwa: "Curry z ciecierzycy", skladniki: ["ryż", "ciecierzyca w puszce", "mleczko kokosowe", "przyprawa curry"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 35},
    {id: 12, nazwa: "Ryż z warzywami na patelnię", skladniki: ["ryż", "mieszanka warzyw mrożonych", "przyprawy"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 30},
    {id: 13, nazwa: "Kaszotto pieczarkowe", skladniki: ["kasza gryczana", "pieczarki", "cebula", "kostka rosołowa"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 32},
    {id: 14, nazwa: "Ryż z fasolą po meksykańsku", skladniki: ["ryż", "fasola czerwona", "kukurydza", "przecier pomidorowy"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 33},
    {id: 15, nazwa: "Jajecznica z cebulką", skladniki: ["jajka", "cebula", "masło", "chleb"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 18},
    {id: 16, nazwa: "Jajka sadzone z ziemniakami", skladniki: ["jajka", "ziemniaki", "kefir"], czas: "powyżej 15 min", porcje: 1, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 22},
    {id: 17, nazwa: "Szakszuka (Jajka w pomidorach)", skladniki: ["jajka", "pomidory w puszce", "cebula", "czosnek"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 25},
    {id: 18, nazwa: "Omlet z serem i szynką", skladniki: ["jajka", "ser żółty", "szynka", "mleko"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "standard", cena_restauracja: 24},
    {id: 19, nazwa: "Pasta jajeczna", skladniki: ["jajka", "majonez", "szczypiorek", "chleb"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 20},
    {id: 20, nazwa: "Tofucznica (Wegańska jajecznica)", skladniki: ["tofu", "cebula", "kurkuma", "pomidor"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "wegańska", cena_restauracja: 26},
    {id: 21, nazwa: "Grzanki z serem (Grilled Cheese)", skladniki: ["chleb", "ser żółty", "masło"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 18},
    {id: 22, nazwa: "Tosty francuskie", skladniki: ["chleb tostowy", "jajka", "mleko", "cukier"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 22},
    {id: 23, nazwa: "Pizza z tortilli", skladniki: ["tortilla", "ser żółty", "sos pomidorowy", "szynka"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "standard", cena_restauracja: 25},
    {id: 24, nazwa: "Wrap z kurczakiem i warzywami", skladniki: ["tortilla", "kurczak", "sałata", "pomidor", "sos czosnkowy"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "standard", cena_restauracja: 28},
    {id: 25, nazwa: "Wrap z hummusem i warzywami", skladniki: ["tortilla", "hummus", "papryka", "ogórek"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegańska", cena_restauracja: 24},
    {id: 26, nazwa: "Bruschetta bieda-style", skladniki: ["chleb", "pomidor", "czosnek", "oliwa"], czas: "do 15 min", porcje: 1, lunchbox: false, dieta: "wegańska", cena_restauracja: 20},
    {id: 27, nazwa: "Zapiekanki z pieczarkami", skladniki: ["bułka", "pieczarki", "cebula", "ser żółty"], czas: "do 15 min", porcje: 2, lunchbox: false, dieta: "wegetariańska", cena_restauracja: 30},
    {id: 28, nazwa: "Pieczone ziemniaczki", skladniki: ["ziemniaki", "oliwa", "przyprawy"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 22},
    {id: 29, nazwa: "Placki ziemniaczane", skladniki: ["ziemniaki", "cebula", "jajka", "mąka"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 26},
    {id: 30, nazwa: "Kopytka leniwe", skladniki: ["twaróg", "jajka", "mąka"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 24},
    {id: 31, nazwa: "Ziemniaki z gzikiem", skladniki: ["ziemniaki", "twaróg", "śmietana", "szczypiorek"], czas: "powyżej 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 20},
    {id: 32, nazwa: "Sałatka grecka", skladniki: ["sałata", "pomidor", "ogórek", "ser feta", "oliwki"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 32},
    {id: 33, nazwa: "Sałatka z makaronem i szynką", skladniki: ["makaron", "szynka", "ogórek kwaszony", "majonez"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 28},
    {id: 34, nazwa: "Caprese", skladniki: ["pomidor", "mozarella", "bazylia", "oliwa"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 26},
    {id: 35, nazwa: "Sałatka nicejska (wersja tania)", skladniki: ["sałata", "jajka", "tuńczyk w puszce", "pomidor"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "standard", cena_restauracja: 30},
    {id: 36, nazwa: "Zupa pomidorowa z ryżem", skladniki: ["rosół (z kostki)", "koncentrat pomidorowy", "ryż", "śmietana"], czas: "do 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 24},
    {id: 37, nazwa: "Krem z groszku", skladniki: ["groszek mrożony", "cebula", "ziemniak", "mięta"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 22},
    {id: 38, nazwa: "Rosół studencki", skladniki: ["udko kurczaka", "włoszczyzna mrożona", "makaron"], czas: "powyżej 15 min", porcje: 4, lunchbox: true, dieta: "standard", cena_restauracja: 28},
    {id: 39, nazwa: "Zupa ogórkowa", skladniki: ["ogórki kiszone", "ziemniaki", "włoszczyzna", "śmietana"], czas: "powyżej 15 min", porcje: 4, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 26},
    {id: 40, nazwa: "Owsianka na mleku", skladniki: ["płatki owsiane", "mleko", "banan", "orzechy"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 18},
    {id: 41, nazwa: "Owsianka nocna (overnight oats)", skladniki: ["płatki owsiane", "jogurt", "owoce mrożone"], czas: "do 15 min", porcje: 1, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 20},
    {id: 42, nazwa: "Parówki z serem w cieście francuskim", skladniki: ["parówki", "ciasto francuskie", "ser żółty"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "standard", cena_restauracja: 28},
    {id: 43, nazwa: "Naleśniki z dżemem", skladniki: ["mąka", "mleko", "jajka", "dżem"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 26},
    {id: 44, nazwa: "Naleśniki ze szpinakiem", skladniki: ["mąka", "mleko", "jajka", "szpinak mrożony"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 28},
    {id: 45, nazwa: "Placuszki z jabłkami (Racuchy)", skladniki: ["mąka", "kefir", "jajka", "jabłka"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 24},
    {id: 46, nazwa: "Budyń jaglany", skladniki: ["kasza jaglana", "mleko", "banan", "kakao"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 22},
    {id: 47, nazwa: "Leczo warzywne", skladniki: ["papryka", "cukinia", "pomidory w puszce", "cebula"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "wegańska", cena_restauracja: 30},
    {id: 48, nazwa: "Leczo z kiełbasą", skladniki: ["kiełbasa", "papryka", "cukinia", "pomidory w puszce"], czas: "powyżej 15 min", porcje: 3, lunchbox: true, dieta: "standard", cena_restauracja: 35},
    {id: 49, nazwa: "Kotlety z jajek", skladniki: ["jajka gotowane", "bułka tarta", "szczypiorek", "surowe jajko"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegetariańska", cena_restauracja: 24},
    {id: 50, nazwa: "Mielone z fasoli", skladniki: ["fasola czerwona w puszce", "cebula", "bułka tarta", "przyprawy"], czas: "powyżej 15 min", porcje: 2, lunchbox: true, dieta: "wegańska", cena_restauracja: 28}
];
